// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma Migrate uses the standard sqlite file: scheme
    // The runtime adapter (src/lib/prisma.ts) uses libsql:file: separately
    url: "file:./dev.db",
  },
});
